- name: Initialize Kubernetes cluster on master node
  hosts: k8s_master
  become: true
  become_method: sudo
  vars:
    k8s_version: "1.30"
    pod_network_cidr: "10.244.0.0/16"
    ansible_become_password: "1234"
    admin_user: "admin"
  tasks:
    - name: Create admin user
      ansible.builtin.user:
        name: "{{ admin_user }}"
        state: present
        shell: /bin/bash
        home: /home/{{ admin_user }}
        create_home: true
        group: "{{ admin_user }}"
        groups: sudo  # Add to sudo group for admin privileges
        append: yes   # Append to groups without removing others
        password: "{{ 'your_secure_password' | password_hash('sha512') }}"  # Set a secure password
      register: admin_user_created
    # - name: Initialize cluster with kubeadm
    #   ansible.builtin.shell: |
    #     kubeadm init \
    #       --pod-network-cidr {{ pod_network_cidr }} \
    #       --service-cidr 10.96.0.0/12 \
    #       --kubernetes-version v{{ k8s_version }}.3 \
    #       --apiserver-advertise-address {{ ansible_default_ipv4.address }} \
    #       --apiserver-cert-extra-sans {{ ansible_hostname }}
    #   args:
    #     creates: /etc/kubernetes/admin.conf
    #   register: kubeadm_init

    - name: Create .kube directory for admin user
      ansible.builtin.file:
        path: /home/admin/.kube
        state: directory
        owner: admin
        group: admin
        mode: 0755

    - name: Copy admin config to user directory
      ansible.builtin.shell: |
        cp -f /etc/kubernetes/admin.conf /home/admin/.kube/config
        chown admin:admin /home/admin/.kube/config

    - name: Extract join command from kubeadm output
      ansible.builtin.set_fact:
        join_command: "{{ kubeadm_init.stdout | regex_search('kubeadm join.*?--token') }}"

    - name: Save join command to file
      ansible.builtin.copy:
        content: "{{ join_command }}"
        dest: /tmp/k8s_join_command.txt
        owner: admin
        group: admin
        mode: 0644

    - name: Display join command for verification
      ansible.builtin.debug:
        msg: "Join command: {{ join_command }}"

    - name: Wait for Kubernetes API to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: 6443
        delay: 10
        timeout: 120




