---
- name: Setup kubectl access on ansible-control node
  hosts: k8s_master
  become: yes
  become_method: "su"
  vars:
    ansible_become_password: "1234"
    ansible_control_name: "127.0.0.1"
    admin_user: "admin"
  tasks:
    - name: "ШАГ 1: Определяю текущего пользователя"
      ansible.builtin.shell: |
        whoami
      register: whoami_output
      delegate_to: "{{ ansible_control_name }}"
      become: false
      
    - name: "ШАГ 2: Показываю результат"
      ansible.builtin.debug:
        msg: "Текущий пользователь: {{ whoami_output.stdout }}"
      
    - name: Copy kubeconfig to ansible-control node
      ansible.builtin.fetch:
        src: /home/admin/.kube/config
        dest: /home/{{ whoami_output.stdout }}/.kube/config
        flat: yes
      become_user: "root"
        
    - name: Set correct permissions on kubeconfig
      ansible.builtin.file:
        path: /home/{{ whoami_output.stdout }}/.kube/config
        owner: semaphore
        mode: 0777
      delegate_to: "{{ ansible_control_name }}"
      become_user: "root"

    - name: Install kubectl on ansible-control node
      package:
        name: kubectl
        state: present
      delegate_to: "{{ ansible_control_name }}"
      become_user: "root"

    - name: Copy admin config to user directory
      ansible.builtin.shell: |
        export KUBECONFIG=/home/{{ whoami_output.stdout }}/.kube/config
      delegate_to: "{{ ansible_control_name }}"
        
    - name: Verify kubectl access
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/{{ whoami_output.stdout }}/.kube/config get nodes
      register: kubectl_nodes
      delegate_to: "{{ ansible_control_name }}"
      become_user: "root"
      
    - name: Display nodes info
      ansible.builtin.debug:
        msg: "{{ kubectl_nodes.stdout }}"
      delegate_to: "{{ ansible_control_name }}"















































