---
- name: Setup kubectl access on ansible-control node
  hosts: k8s_master
  become: true
  become_method: sudo
  vars:
    ansible_become_password: "1234"
    ansible_control_name: "127.0.0.1"
  tasks:
    - name: Copy kubeconfig to ansible-control node
      ansible.builtin.fetch:
        src: /home/admin/.kube/config
        dest: /home/admin/.kube/config
        flat: yes
        
    - name: Update kubeconfig with master node IP
      ansible.builtin.replace:
        path: /home/admin/.kube/config
        regexp: 'server: https://127.0.0.1:6443'
        replace: "server: https://{{ hostvars['k8s-master-01']['ansible_default_ipv4']['address'] }}:6443"
      delegate_to: "{{ ansible_control_name }}"

    - name: Set correct permissions on kubeconfig
      ansible.builtin.file:
        path: /home/admin/.kube/config
        owner: admin
        group: admin
        mode: 0600
      delegate_to: "{{ ansible_control_name }}"

    - name: Install kubectl on ansible-control node
      package:
        name: kubectl
        state: present
      delegate_to: "{{ ansible_control_name }}"

    - name: Verify kubectl access
      ansible.builtin.shell: |
        kubectl get nodes
      register: kubectl_nodes
      delegate_to: "{{ ansible_control_name }}"

    - name: Display nodes info
      ansible.builtin.debug:
        msg: "{{ kubectl_nodes.stdout }}"







