- name: Install Calico network plugin
  hosts: k8s_master
  become: true
  become_method: sudo
  vars:
    ansible_become_password: "1234"
  tasks:
    - name: Apply Calico manifest
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/admin/.kube/config apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml
    
    - name: Wait for calico-node to be ready
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/admin/.kube/config wait --for=condition=ready pod -l k8s-app=calico-node -n kube-system --timeout=300s
      
    - name: Wait for calico-kube-controllers to be ready
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/admin/.kube/config wait --for=condition=ready pod -l k8s-app=calico-kube-controllers -n kube-system --timeout=300s
      
    - name: Check nodes
      ansible.builtin.shell: |
        kubectl --kubeconfig=/home/admin/.kube/config get nodes
      register: nodes
    
    - name: Show nodes
      debug:
        msg: "{{ nodes.stdout }}"







