- name: My First Ansible Playbook
  hosts: web-servers
  gather_facts: true
  become: true
  become_method: sudo
  vars:
    ansible_become_password: "your_sudo_password_here"
  tasks:
    - name: Update apt package cache (for Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx package
      package:
        name: nginx
        state: present

    - name: Start and Enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy index.html
      copy:
        content: "<h1>Hello from {{ ansible_hostname }}!</h1>"
        dest: /var/www/html/index.html

